// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var Prisma = /* module */[];

var Context = /* module */[];

var DataSources = /* module */[];

var Resolvers = /* module */[];

exports.Prisma = Prisma;
exports.Context = Context;
exports.DataSources = DataSources;
exports.Resolvers = Resolvers;
/* No side effect */
