// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var PostParent = /* module */[];

var post = {
  id: (function (parent) {
      return parent.id;
    }),
  createdAt: (function (parent) {
      return parent.createdAt;
    }),
  updatedAt: (function (parent) {
      return parent.updatedAt;
    }),
  isPublished: (function (parent) {
      return parent.isPublished;
    }),
  title: (function (parent) {
      return parent.title;
    }),
  content: (function (parent) {
      return parent.content;
    }),
  author: (function (parent, _, ctx) {
      return ctx.db.post({
                    id: parent.id
                  }).author();
    })
};

exports.PostParent = PostParent;
exports.post = post;
/* No side effect */
