// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var QueryParent = /* module */[];

var query = {
  feed: (function (_, _$1, ctx) {
      return ctx.db.posts({
                  where: {
                    isPublished: true
                  }
                });
    }),
  drafts: (function (_, _$1, ctx) {
      return ctx.db.posts({
                  where: {
                    isPublished: false
                  }
                });
    }),
  post: (function (_, args, ctx) {
      return ctx.db.post({
                  id: args.id
                });
    })
};

exports.QueryParent = QueryParent;
exports.query = query;
/* No side effect */
