// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Post$ReasonApolloServerPrisma = require("./Post.bs.js");
var User$ReasonApolloServerPrisma = require("./User.bs.js");
var Query$ReasonApolloServerPrisma = require("./Query.bs.js");
var Mutation$ReasonApolloServerPrisma = require("./Mutation.bs.js");

var resolvers = {
  Query: Query$ReasonApolloServerPrisma.query,
  Mutation: Mutation$ReasonApolloServerPrisma.mutation,
  Post: Post$ReasonApolloServerPrisma.post,
  User: User$ReasonApolloServerPrisma.user
};

exports.resolvers = resolvers;
/* No side effect */
