// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ApolloServer = require("apollo-server");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function Make() {
  var createApolloServer = function (typeDefs, resolvers, datasources, context, engine, _) {
    return new ApolloServer.ApolloServer({
                typeDefs: typeDefs,
                resolvers: resolvers,
                datasources: Js_null_undefined.fromOption(datasources),
                context: Js_null_undefined.fromOption(context),
                engine: Js_null_undefined.fromOption(engine)
              });
  };
  return /* module */[/* createApolloServer */createApolloServer];
}

exports.Make = Make;
/* apollo-server Not a pure module */
